
drop database if exists live_work_chill_db

create database live_work_chill

use live_work_chill

CREATE TABLE CURRENT_RENTS (
ID INT NOT NULL AUTO_INCREMENT,
STATE VARCHAR (100) NOT NULL,
REGION VARCHAR (100) NOT NULL,
RENT DECIMAL (10,2),
TYPE VARCHAR (100),
PRIMARY KEY (ID));

CREATE TABLE USER_INFO (
ID INT NOT NULL AUTO_INCREMENT,
FIRST_NAME VARCHAR (100) NOT NULL,
LAST_NAME VARCHAR (100) NOT NULL,
WORK_ZIP INT NOT NULL,
CURRENT_SALARY INT NOT NULL,
PRIMARY KEY (ID));